"""empty message

Revision ID: 83654efff710
Revises: c7ddad32d3e4
Create Date: 2026-01-06 14:57:41.724102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83654efff710'
down_revision = 'c7ddad32d3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_salary', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('hourly_rate', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('annual_leave', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sick_leave', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('sick_leave')
        batch_op.drop_column('annual_leave')
        batch_op.drop_column('hourly_rate')
        batch_op.drop_column('monthly_salary')

    # ### end Alembic commands ###
