"""empty message

Revision ID: c7ddad32d3e4
Revises: 482039d9fddf
Create Date: 2025-12-29 15:20:35.381828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ddad32d3e4'
down_revision = '482039d9fddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'car', ['car_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('car_id')

    # ### end Alembic commands ###
